
project_id = "azikiiztfejmywbhtuak"

[api]
enabled = true
port = 55508
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55509
shadow_port = 55510
major_version = 15

[studio]
enabled = true
port = 55511
api_url = "http://localhost"

[inbucket]
enabled = true
port = 55512

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://localhost:3000",
  "https://3c7ee4eb-63ae-4ed8-8d9d-9d1710f7c25f.lovableproject.com",
  "https://azikiiztfejmywbhtuak.supabase.co/auth/v1/callback",
  "http://localhost:5111",
  "https://localhost:5111"
]
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""
url = ""

[functions]
[functions.payment-webhook]
verify_jwt = false
[functions.mtn-momo]
verify_jwt = false
[functions.airtel-money]
verify_jwt = false

[functions.hello-world]
enabled = true
verify_jwt = true
import_map = "./functions/hello-world/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello-world/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello-world/*.html" ]

[functions.test-analysis]
enabled = true
verify_jwt = true
import_map = "./functions/test-analysis/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-analysis/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-analysis/*.html" ]

[functions.appointment-reminder]
enabled = true
verify_jwt = true
import_map = "./functions/appointment-reminder/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/appointment-reminder/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/appointment-reminder/*.html" ]

[functions.cv-optimizer]
enabled = true
verify_jwt = true
import_map = "./functions/cv-optimizer/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cv-optimizer/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cv-optimizer/*.html" ]

[functions.email-notifications]
enabled = true
verify_jwt = true
import_map = "./functions/email-notifications/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/email-notifications/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/email-notifications/*.html" ]
