'use strict';
const VERSION='makoki-guidance-policy-v1';
const PERMISSIONS=Object.freeze(['guidance.read_assigned','guidance.comment','guidance.propose_reformulation','guidance.follow_up']);
const INTERVENTION_TYPES=Object.freeze(['comment','reformulation_proposed','follow_up','disagreement','correction_requested']);
class GuidancePolicyError extends Error{constructor(code,message){super(message);this.code=code;}}
const freeze=(v)=>{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
const req=(v,f)=>{if(typeof v!=='string'||!v.trim())throw new GuidancePolicyError('GUIDANCE_FIELD_REQUIRED',`${f} required`);return v.trim();};
const createConsentLedger=({beneficiaryAccountId,scope})=>freeze({schemaVersion:VERSION,beneficiaryAccountId:req(beneficiaryAccountId,'beneficiaryAccountId'),scope:req(scope,'scope'),events:[]});
const appendConsentDecision=(ledger,input)=>{if(input.actorAccountId!==ledger.beneficiaryAccountId)throw new GuidancePolicyError('GUIDANCE_CONSENT_OWNER_REQUIRED','Only beneficiary can decide consent');if(!['granted','revoked'].includes(input.decision))throw new GuidancePolicyError('GUIDANCE_CONSENT_DECISION_INVALID','Invalid decision');if(ledger.events.some(e=>e.eventId===input.eventId))throw new GuidancePolicyError('GUIDANCE_EVENT_DUPLICATE','Append-only ids');return freeze({...ledger,events:[...ledger.events,{eventId:req(input.eventId,'eventId'),decision:input.decision,actorAccountId:input.actorAccountId,decidedAt:new Date(req(input.decidedAt,'decidedAt')).toISOString(),reason:req(input.reason,'reason')}]});};
const authorizeGuidance=({actor,beneficiaryAccountId,assignment,consent,permission})=>{if(actor?.role==='beneficiary'){const allowed=actor.accountId===beneficiaryAccountId;return freeze({allowed,reason:allowed?'owner':'not_owner'});}if(!['advisor','coach'].includes(actor?.role)||!PERMISSIONS.includes(permission))return freeze({allowed:false,reason:'role_or_permission_unknown'});if(assignment?.active!==true||assignment.actorAccountId!==actor.accountId||assignment.beneficiaryAccountId!==beneficiaryAccountId||assignment.role!==actor.role)return freeze({allowed:false,reason:'not_assigned'});if(!actor.permissions?.includes(permission))return freeze({allowed:false,reason:'permission_missing'});if(consent?.beneficiaryAccountId!==beneficiaryAccountId||consent.events?.at(-1)?.decision!=='granted')return freeze({allowed:false,reason:'consent_missing_or_revoked'});return freeze({allowed:true,reason:'assigned_permission_and_consent'});};
const appendIntervention=(journal,input)=>{if(!['beneficiary','advisor','coach'].includes(input?.actorRole))throw new GuidancePolicyError('GUIDANCE_ROLE_INVALID','Invalid actor role');if(!INTERVENTION_TYPES.includes(input?.type))throw new GuidancePolicyError('GUIDANCE_INTERVENTION_INVALID','Invalid intervention type');const events=journal?.events||[];if(events.some(e=>e.eventId===input.eventId))throw new GuidancePolicyError('GUIDANCE_EVENT_DUPLICATE','Append-only ids');return freeze({schemaVersion:VERSION,events:[...events,{eventId:req(input.eventId,'eventId'),type:req(input.type,'type'),actorAccountId:req(input.actorAccountId,'actorAccountId'),actorRole:req(input.actorRole,'actorRole'),beneficiaryAccountId:req(input.beneficiaryAccountId,'beneficiaryAccountId'),subjectRef:req(input.subjectRef,'subjectRef'),recordedAt:new Date(req(input.recordedAt,'recordedAt')).toISOString(),text:req(input.text,'text'),replacesUserStatement:false}]});};
module.exports={VERSION,PERMISSIONS,INTERVENTION_TYPES,GuidancePolicyError,appendConsentDecision,appendIntervention,authorizeGuidance,createConsentLedger};
